### ISSUE TITLE
Loading image by selector broken in A-Frame 6

### ISSUE THREAD

**Issue by sigoetti** [bryik/stereo-panorama-viewer#5]
Hi Ben, thanks for this component. In A-Frame 6.x loading the images by selector doesn't work anymore. Example:

This works:
` <a-entity overunder="../assets/witness_painter.jpg"></a-entity>`

This doesn't work:
` <a-assets>    <img id="witness" src="../assets/witness_painter.jpg">  </a-assets>
  <a-entity overunder="#witness"></a-entity>`

My temporary workaround is to change this line
` var texture = new THREE.TextureLoader().load( this.data );`
to this
`var texture = new THREE.TextureLoader().load(this.data.getAttribute('src'));`
but this breaks the loading by URL part. 

Do you have any idea how to fix this? I'm still new to A-Frame.

**Comment by bryik** [comment]
A-Frame 0.6.1 brought changes to the asset management system (one of which causes this break). However, that's not the real problem. The real problem is that this component never properly interfaced with the asset management system. I thought it did, but any image placed in `<a-assets>` is actually downloaded twice (once through A-Frame's asset system, then again through this component's texture loader). 

The "solution" is just to load images inline.

```html
<a-entity id="display" overunder="../assets/witness_painter.jpg"></a-entity>
```

Loading by selector could be fixed, but it's pointless to do so until I can figure out how to better integrate with the asset system.

**Comment by bryik** [comment]
I have updated the examples and README.

**Comment by bryik** [comment]
I'm going to close this issue as the project has changed significantly.
